[package]
name = "bft"
version = "0.1.0"
authors = ["Chris Shepherd"]

[workspace]
members = [
  "bft_types",
  "bft_interp"
]

[dependencies]
bft_types = { path = "bft_types" }
bft_interp = { path = "bft_interp" }
